const ACTION_PREFIX = "__INVITE_USER__"

export const OPEN_INVITE_MODAL = ACTION_PREFIX + "OPEN_INVITE_MODAL"
export const CLOSE_INVITE_MODAL = ACTION_PREFIX + "CLOSE_INVITE_MODAL"
export const VALIDATE_INPUT = ACTION_PREFIX + "VALIDATE_INPUT"
export const SENDING_INVITE = ACTION_PREFIX + "SENDING_INVITE"
export const INVITE_SENT = ACTION_PREFIX + "INVITE_SENT"
export const INVITATIONS_ERROR = ACTION_PREFIX + "INVITATIONS_ERROR"
