const ACTION_PREFIX = "__PLATFORM_NOTIFICATIONS__"

export const PLATFORM_NOTIFICATIONS_TARGET_FETCHING =
  ACTION_PREFIX + "TARGET_FETCHING"
export const PLATFORM_NOTIFICATIONS_TARGET_SUCCESS =
  ACTION_PREFIX + "TARGET_SUCCESS"
export const PLATFORM_NOTIFICATIONS_TARGET_ERROR =
  ACTION_PREFIX + "TARGET_ERROR"
export const PLATFORM_NOTIFICATIONS_TARGET_CLEAR =
  ACTION_PREFIX + "CLEAR_TARGET"

export const PLATFORM_NOTIFICATIONS_TARGET_IS_READ =
  ACTION_PREFIX + "TARGET_IS_READ"

export const PLATFORM_NOTIFICATIONS_FETCHING = ACTION_PREFIX + "FETCHING"
export const PLATFORM_NOTIFICATIONS_SUCCESS = ACTION_PREFIX + "SUCCESS"
export const PLATFORM_NOTIFICATIONS_ERROR = ACTION_PREFIX + "ERROR"
